# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9d58caed92d898a6140d4076e6de32d488b0a48eeba52e58e407e5dbbc7ebc2e448ac2306b5e4ea9c2f67977b53e89b2e2777d498fd6f50903644c70b9eb6e

test:
  secret_key_base: 193f2ade706cc478dffae4db9151e7a2804571eab8575989b941eae8d14a4e45460652cb1ce9a386fd4ce128a9c28d9d6a529a43ae8a4b033c0a0e507faf43b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
